"""add user_id to tasks

Revision ID: a40d598384b7
Revises: 14717f4102be
Create Date: 2026-02-16 15:15:42.609002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a40d598384b7'
down_revision: Union[str, None] = '14717f4102be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Добавляем колонку как nullable, чтобы не сломать существующие строки
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=True))

    # 2. Заполняем существующие задачи — привязываем к первому пользователю
    op.execute('UPDATE tasks SET user_id = (SELECT id FROM users LIMIT 1) WHERE user_id IS NULL')

    # 3. Теперь делаем колонку обязательной
    op.alter_column('tasks', 'user_id', nullable=False)

    # 4. Добавляем внешний ключ
    op.create_foreign_key('fk_tasks_user_id', 'tasks', 'users', ['user_id'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tasks_user_id', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'user_id')
    # ### end Alembic commands ###
